function f() {
    return 118 == j ? r << a : 16 == j ? r == a : 103 == j ? null : 6 == j ? i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n, 0, i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n), i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n)) : 94 == j ? r != a : 80 == j ? ~i(l, r, a, n) : 2 == j ? r <= a : 59 == j ? (we = i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n, !0),
        Fe = i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n),
        we instanceof i.constructor ? i.apply.call(we, n[0].n, Fe) : (be = we[0][we[1]],
            we[0] instanceof i.g ? i.apply.call(be, n.n, Fe) : i.apply.call(be, we[0], Fe))) : 52 == j ? r !== a : 68 == j ? r / a : 75 == j ? r ? --a[0][a[1]] : a[0][a[1]]-- : 46 == j ? (61 == (ce = l[C++]) && (Ce = l[C++]),
    53 == ce && (m = i(l, C, -2),
        C = m.i,
        Ce = m.n),
    70 == ce && (Ce = parseFloat(i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n))),
        Ce) : 69 == j ? r[0][r[1]] /= a : 85 == j ? !i(l, r, a, n) : 111 == j ? r in a : 87 == j ? undefined : 120 == j ? (n.a = !0,
        i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n)) : 62 == j ? r >> a : 93 == j ? r instanceof a : 81 == j ? (n.t && n.t[n.t.length - 1]).s = !0 : 110 == j ? r % a : 78 == j ? (n.m = !0,
        je = i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n),
        n.m = !1,
        g[je] = n.u,
        i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n)) : 95 == j ? n.n : 38 == j ? r || i(l, a, u, n) : 121 == j ? r[0][r[1]] |= a : 60 == j ? i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n, 0, i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n), C++, (m = i(l, C, -3),
        C = m.i,
        m.n)) : 63 == j ? r * a : 19 == j ? r[0][r[1]] -= a : 92 == j ? r && i(l, a, u, n) : 1 == j ? (ce = i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n),
        n.m = !i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n),
        he = i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n),
        n.m = !1,
        [ce, he, pe = i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n)]) : 30 == j ? r & a : 24 == j ? +i(l, r, a, n) : 101 == j ? r >= a : 91 == j ? i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n, 0, C++, (m = i(l, C, -3),
        C = m.i,
        m.n)) : 57 == j ? i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n).pop() : 77 == j ? !((ue = i(l, r, a, n, !0))[0] instanceof i.g) && delete ue[0][ue[1]] : 119 == j ? r ? ++a[0][a[1]] : a[0][a[1]]++ : 116 == j ? i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n) : 102 == j ? -i(l, r, a, n) : 37 == j ? r | a : 10 == j ? r[0][r[1]] %= a : 72 == j ? (xe = i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n),
        G = i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n),
        n.m = !xe,
        Ee = i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n),
        n.m = !1,
        t ? [G, Ee] : G[Ee]) : 3 == j ? (n.m = !0,
        Re = i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n),
        n.m = !1,
        Se = i(l, C++, (m = i(l, C, -3),
            C = m.i,
            m.n), n),
        g[Re] = Se,
        n.e ? [g, Re] : void 0) : 45 == j ? !!l[C++] : 36 == j ? r < a : 74 == j ? new RegExp(i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n), i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n)) : 97 == j ? r[0][r[1]] >>>= a : 125 == j ? typeof i(l, r, a, n) : 43 == j ? r > a : 15 == j ? r ^ a : 126 == j ? i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n) : 21 == j ? i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n, 0, i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n, !0), i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n)) : 96 == j ? i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n, 0, i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n), i(l, C++, (m = i(l, C, -3),
        C = m.i,
        m.n), n, !0)) : 8 == j ? r[0][r[1]] += a : 113 == j ? r - a : 58 == j ? r + a : 104 == j ? (n.t && n.t[n.t.length - 1]).v = !0 : 26 == j ? r === a : 86 == j ? r[0][r[1]] = a : 64 == j ? r >>> a : void 0
}
